import assert from 'node:assert/strict';
import { createGame, playerAgency, advanceDay, dailyUpkeep } from '../src/engine/game.js';
import { ensurePersonnel, contractProposal, negotiatePersonnel, releaseQuote, releaseContract, transferQuote, hireCoach, assignCamp, tickPersonnel } from '../src/engine/personnel.js';
import { snapshotGame, restoreGame } from '../src/engine/checkpoint.js';
import { registerYouth, ensureSeason } from '../src/engine/season.js';
import { transferOffers, sellYouth } from '../src/engine/career.js';
import { renderPersonnel } from '../src/ui/personnel.js';
import { youthCandidates } from '../src/data/youth-candidates.js';
const g=await createGame({seed:174,agencyChoiceId:'player-major',careerStart:true});g.opening.tutorialContractNeeded=false;
ensurePersonnel(g);const a=playerAgency(g),t=a.roster[0];
const before=a.funds,offer=contractProposal(g,t);
assert(negotiatePersonnel(g,t.id,offer,{renew:true}).ok);assert.equal(a.funds,before-offer.signing);
const after=a.funds;assert(!negotiatePersonnel(g,t.id,offer,{renew:true}).ok);assert.equal(a.funds,after);
assert(hireCoach(g,'development').ok);assert(!hireCoach(g,'development').ok);
const campT=a.roster[1],ca=campT.stats.judge;assert(assignCamp(g,campT.id,'judge','development').ok);
assert(!assignCamp(g,a.roster[2].id,'judge','development').ok);
const beforeCamp=restoreGame(snapshotGame(g));
for(let i=0;i<5;i++)await advanceDay(g);
assert(!campT.camp);assert(campT.stats.judge>ca);assert.equal(g.log.filter(r=>r.camps?.length).length,5);
for(let i=0;i<5;i++)await advanceDay(beforeCamp);
assert.deepEqual(snapshotGame(g),snapshotGame(beforeCamp));
const youth=a.roster.find(x=>x.isYouth),cup=ensureSeason(g).events.find(e=>e.date===7);
assert(registerYouth(g,cup.id,youth.id).ok);assert(!assignCamp(g,youth.id,'judge','development').ok);
const wage=dailyUpkeep(g)*7;assert(wage>=20);
await advanceDay(g);const payReport=await advanceDay(g);
assert.equal(payReport.upkeep,a.roster.reduce((sum,t)=>sum+t.contract.wage,0)+20);
const freeFee=releaseQuote(g,t.id),party=structuredClone(t.party),funds=a.funds;
assert(releaseContract(g,t.id,freeFee).ok);assert.equal(a.funds,funds-freeFee);assert(!a.roster.includes(t));assert(g.personnel.freeAgents.includes(t));assert.deepEqual(t.party,party);
assert(!releaseContract(g,t.id,freeFee).ok);
g.day=50;assert(negotiatePersonnel(g,t.id,contractProposal(g,t),{quotedFee:0}).ok);assert(a.roster.includes(t));assert(!g.personnel.freeAgents.includes(t));
const rival=g.league.agencies.find(x=>x.id!==a.id&&x.roster.length>1),target=rival.roster[0],q=transferQuote(g,target.id);
assert(q);assert(!negotiatePersonnel(g,target.id,contractProposal(g,target),{quotedFee:q.fee}).ok);
g.day=15;const sellerFunds=rival.funds,playerFunds=a.funds,o=contractProposal(g,target);
assert(!negotiatePersonnel(g,target.id,o,{quotedFee:q.fee+1}).ok);assert.equal(a.funds,playerFunds);
assert(negotiatePersonnel(g,target.id,o,{quotedFee:q.fee}).ok);assert.equal(rival.funds,sellerFunds+q.fee);assert.equal(a.funds,playerFunds-q.fee-o.signing);assert(a.roster.includes(target));assert(!rival.roster.includes(target));
const exp=a.roster.find(x=>x.id!==target.id);exp.contract.endsOn=g.day;tickPersonnel(g);assert(!a.roster.includes(exp));assert(g.personnel.freeAgents.includes(exp));
const legacy=snapshotGame(g);legacy.snapshotVersion=4;delete legacy.personnel;for(const ag of legacy.league.agencies)for(const tr of ag.roster){delete tr.contract.endsOn;tr.contract.signedOnDay=1;tr.contract.years=1;}legacy.day=1000;
const migrated=restoreGame(legacy);assert(migrated.league.agencies.every(ag=>ag.roster.every(tr=>tr.contract.endsOn>=1030)));assert.equal(migrated.rng.getState(),g.rng.getState());
assert(youthCandidates(g).every(c=>!g.personnel.freeAgents.some(t=>t.id===`y-${c.id}`)));
console.log('PASS: renewal/duplicate charge, coach wages, camp duration/growth/save, overlap, release/FA, transfer money/ownership, expiry, v4 grace migration');

// A graduation sale must not bypass the active-camp transfer guard.
const campGame=await createGame({seed:174,agencyChoiceId:'player-major',careerStart:true});
ensurePersonnel(campGame);const campAgency=playerAgency(campGame),graduate=campAgency.roster.find(t=>t.isYouth);graduate.legacyPro=true;
const bid=transferOffers(campGame,graduate.id)[0];assert(bid);
assert(hireCoach(campGame,'development').ok);assert(assignCamp(campGame,graduate.id,'judge','development').ok);
const campSnapshot=snapshotGame(campGame);
assert.deepEqual(transferOffers(campGame,graduate.id),[]);
assert(!sellYouth(campGame,graduate.id,bid.agencyId,bid.fee).ok);
assert.deepEqual(snapshotGame(campGame),campSnapshot);
assert.match(renderPersonnel(campGame),/지도 가능한 코치가 없습니다/);
assert.match(renderPersonnel(campGame),/id="camp-start" disabled/);
console.log('PASS: camp blocks stale graduation sale without state changes; busy coach unavailable');
